version: '2'
services:
  redis:
    container_name: redis
    image: 'redis'
    ports:
      - "6379:6379"
    networks:
      - redis-network
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    networks:
      - redis-network
networks:
  redis-network:
    driver: bridge